# Generated by Django 4.0.1 on 2022-07-31 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academyapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevelthree',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_level_three', to='academyapp.categoryleveltwo'),
        ),
        migrations.AlterField(
            model_name='categoryleveltwo',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories_level_two', to='academyapp.categorylevelone'),
        ),
    ]
