# Generated by Django 4.0.1 on 2022-07-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academyapp', '0002_alter_categorylevelthree_sub_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylevelthree',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='academyapp.categoryleveltwo'),
        ),
        migrations.AlterField(
            model_name='categoryleveltwo',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_categories', to='academyapp.categorylevelone'),
        ),
    ]
