# Generated by Django 4.0.1 on 2022-08-06 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academyapp', '0004_alter_categorylevelone_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryLevelThree',
        ),
    ]
