# Generated by Django 4.0.1 on 2022-08-06 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academyapp', '0005_delete_categorylevelthree'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category_level_two',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academyapp.categoryleveltwo', verbose_name='Kategori'),
        ),
    ]
