# Generated by Django 4.0.1 on 2022-08-10 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academyapp', '0006_course_category_level_two'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhichCourseAndStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField(verbose_name='Sıra Numarası')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academyapp.course', verbose_name='Kurs')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Öğrenci')),
            ],
        ),
    ]
